mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', include('coordinator.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon/favicon.ico', permanent=True)),
    path('', include('django.contrib.flatpages.urls')),
]

mysite/coordinator/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone
from changelog.mixins import ChangeLogMixin
from changelog.signals import changelog_save_handler, changelog_delete_handler


class Department(models.Model):
    name = models.CharField(
        max_length=100,
        help_text="Наименование подразделения",
        verbose_name="Наименование",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Подразделение"
        verbose_name_plural = "Подразделения"


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE
    )
    department = models.ForeignKey(
        Department,
        on_delete=models.SET_NULL,
        null=True,
        help_text="Подразделение",
        verbose_name="Подразделение",
    )
    middle_name = models.CharField(
        max_length=100,
        default="",
        blank=True,
        help_text="Отчество",
        verbose_name="Отчество",
    )

    class Meta:
        verbose_name = "Профиль пользователя"
        verbose_name_plural = "Профили пользователей"

    def __str__(self):
        return self.user.__str__()


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Doctor(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text="Укажите учетную запись пользователя",
        verbose_name="Учетная запись",
    )
    name = models.CharField(
        max_length=100,
        help_text="Фамилия И.О.",
        verbose_name="Имя врача",
    )
    department = models.ForeignKey(
        Department,
        on_delete=models.SET_DEFAULT,
        default=1,
        #related_name='doctor_records',
        help_text="Подразделение, к которому привязан врач",
        verbose_name="Подразделение",
    )
    temperature = models.BooleanField(
        default=False,
        help_text="Обслуживает температурные вызовы",
        verbose_name="Температура",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Врач"
        verbose_name_plural = "Врачи"

    def get_absolute_url(self):
        return "/doctor/"

    def get_list_fields(self):
        fields = []
        for field in self._meta.fields:
            fields.append({
                'name': field.name,
                'verbose_name': field.verbose_name,
                'value': field.value_from_object(self)
            })
        return fields

    def get_detail_fields(self):
        fields = []
        for field in self._meta.fields:
            fields.append({
                'name': field.name,
                'verbose_name': field.verbose_name,
                'value': field.value_from_object(self)
            })
        return fields

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural

    def records(self):
        records = Record.objects.filter(doctor=self)
        return records

    def records_by_date(self, date):
        records = Record.objects.filter(doctor=self).filter(start_date__date=date)
        return records


class ServiceType(models.Model):
    name = models.CharField(
        max_length=200,
        help_text="Адрес вызова",
        verbose_name="Адрес",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Вид обслуживания"
        verbose_name_plural = "Виды обслуживания"


class Record(ChangeLogMixin, models.Model):
    start_date = models.DateTimeField(
        default=timezone.now,
        help_text="Дата регистрации вызова",
        verbose_name="Поступил",
    )
    send_date = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Дата/время передачи вызова",
        verbose_name="Передан",
    )
    finish_date = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Дата/время завершения вызова",
        verbose_name="Завершен",
    )
    department = models.ForeignKey(
        Department,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="Подразделение",
        verbose_name="Подразделение",
    )
    doctor = models.ForeignKey(
        Doctor,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="Врач назначенный на вызов",
        verbose_name="Врач",
    )
    address = models.CharField(
        max_length=200,
        default="",
        blank=True,
        help_text="Адрес вызова",
        verbose_name="Адрес",
    )
    address_street = models.CharField(
        max_length=200,
        default="",
        help_text="Улица",
        verbose_name="Улица",
    )
    address_building = models.CharField(
        max_length=10,
        default="",
        help_text="Дом",
        verbose_name="Дом",
    )
    address_apartment = models.CharField(
        max_length=10,
        default="",
        blank=True,
        help_text="Квартира",
        verbose_name="Квартира",
    )
    patient = models.CharField(
        max_length=150,
        default="",
        help_text="Фамилия И.О.",
        verbose_name="Пациент",
    )
    patient_birthdate = models.DateField(
        default='01.01.1900',
        help_text="Дата рождения пациента",
        verbose_name="Дата рождения",
    )
    temperature = models.BooleanField(
        default=False,
        help_text="Температурный вызов",
        verbose_name="Температура",
    )
    service_type = models.ForeignKey(
        ServiceType,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        help_text="Как был обслужен вызов",
        verbose_name="Вид обслуживания",
    )
    record_order = models.IntegerField(
        help_text="Порядковый номер вызова",
        verbose_name="Порядок",
        default=0,
    )

    def get_absolute_url(self):
        # TODO: Костыль - нужно проработать возврат на нужную страницу в зависимости от источника
        #return "/record/%i" % self.id
        return "/"

    def __str__(self):
        temp = "Вызов от " + self.start_date.strftime('%d.%m.%Y') + " по адресу <" +\
               self.address_street + " " +\
               self.address_building + "-" +\
               self.address_apartment +\
               ">"
        if self.doctor is None:
            temp = temp + " не назначен"
        else:
            temp = temp + " назначен " + str(self.doctor)
        return temp

    class Meta:
        verbose_name = "Вызов"
        verbose_name_plural = "Вызовы"
        permissions = [('view_own_record', 'Can view own')]

    def get_address(self):
        return self.address_street + " " + self.address_building + "-" + self.address_apartment

    get_address.short_description = "Адрес"

    def get_list_fields(self):
        fields = []
        for field in self._meta.fields:
            fields.append({
                'name': field.name,
                'verbose_name': field.verbose_name,
                'value': field.value_from_object(self)
            })
        return fields

    def get_detail_fields(self):
        fields = []
        for field in self._meta.fields:
            fields.append({
                'name': field.name,
                'verbose_name': field.verbose_name,
                'value': field.value_from_object(self)
            })
        return fields

    def get_verbose_name(self):
        return self._meta.verbose_name

    def get_verbose_name_plural(self):
        return self._meta.verbose_name_plural

    def is_sent(self):
        return not self.send_date is None

    def is_finish(self):
        return not self.finish_date is None

    def is_temperature(self):
        return self.temperature

    def is_canceled(self):
        if self.service_type:
            return self.service_type.pk == 1
        else:
            return False

    def is_personally(self):
        if self.service_type:
            return self.service_type.pk == 3
        else:
            return False

    def is_telephone(self):
        if self.service_type:
            return self.service_type.pk == 4
        else:
            return False

    @staticmethod
    def unassigned():
        return Record.objects.filter(doctor=None)

    @staticmethod
    def unassigned_by_date(date):
        return Record.objects.filter(doctor=None).filter(start_date__date=date)

    @staticmethod
    def unassigned_by_date_department(date, department):
        return Record.objects.filter(doctor=None).filter(department=department).filter(start_date__date=date)

    def assign(self, doctor):
        self.send_date = None
        self.doctor = doctor
        self.save()
        return

    def cancel(self):
        self.service_type = ServiceType.objects.get(pk=1)
        self.finish_date = timezone.now()
        self.save()
        return

    def send(self):
        self.send_date = timezone.now()
        self.save()
        return

    def finish(self, service_type):
        self.finish_date = timezone.now()
        self.service_type = service_type
        self.save()
        return


post_save.connect(changelog_save_handler, sender=Record)
post_delete.connect(changelog_delete_handler, sender=Record)

mysite/templates/base.html
<!DOCTYPE html>
<html lang="ru">

{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Координатор</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="{% static '/open-iconic/font/css/open-iconic-bootstrap.css' %}">
    <link rel="stylesheet"
          href="{% static 'base.css' %}">
    <script src="{% static '/js/jquery-3.4.1.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <span class="navbar-brand" href="#">Координатор</span>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Открыть меню">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarCollapse" style>
            <ul class="navbar-nav mr-auto">
                {% if perms.coordinator.view_record %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'record_summary' %}">Сводная</a>
                </li>
                {% elif perms.coordinator.view_own_record %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'doctor_schedule' %}">Расписание</a>
                </li>
                {% endif %}
                {% if perms.coordinator.view_doctor %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'doctor_list' %}">Врачи</a>
                </li>
                {% endif %}
                {% if perms.coordinator.view_record %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'record_today' %}">Вызовы</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav mr-auto">
                <li class="navbar-nav">
                    <a class="nav-link active" href="/about/">О проекте</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <span class="navbar-text">
                        Добрый день,
                        {% if user.first_name %}
                            {{ user.first_name }}
                            {% if user.profile %}
                                {% if user.profile.middle_name %}
                                    {{ user.profile.middle_name }}
                                {% endif %}
                            {% endif %}
                        {% else %}
                            {{ user.username }}
                        {% endif %}
                        !
                    </span>
                </li>
                {% if user.is_superuser %}
                <li>
                  <a class="nav-link" href="{% url 'admin:index' %}">Администрирование</a>
                </li>
                {% endif %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                </li>
                {% else %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'login' %}">Войти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="content container">
        {% block content %}
        {% endblock %}
    </div>

</body>

</html>

mysite/templates/base_doctor.html
<!DOCTYPE html>
<html lang="ru">

{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Координатор</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <link href="{% static '/open-iconic/font/css/open-iconic-bootstrap.css' %}"
          rel="stylesheet">
    <script src="{% static '/js/jquery-3.4.1.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <span class="navbar-brand" href="#">Координатор</span>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Открыть меню">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarCollapse" style>
            <ul class="navbar-nav mr-auto">
                {% if perms.coordinator.view_record %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'record_summary' %}">Сводная</a>
                </li>
                {% elif perms.coordinator.view_own_record %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'doctor_schedule' %}">Расписание</a>
                </li>
                {% endif %}
                {% if perms.coordinator.view_doctor %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'doctor_list' %}">Врачи</a>
                </li>
                {% endif %}
                {% if perms.coordinator.view_record %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'record_today' %}">Вызовы</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav mr-auto">
                <li class="navbar-nav">
                    <a class="nav-link active" href="/about/">О проекте</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <span class="navbar-text">
                        Добрый день,
                        {% if user.first_name %}
                            {{ user.first_name }}
                            {% if user.profile %}
                                {% if user.profile.middle_name %}
                                    {{ user.profile.middle_name }}
                                {% endif %}
                            {% endif %}
                        {% else %}
                            {{ user.username }}
                        {% endif %}
                        !
                    </span>
                </li>
                {% if user.is_superuser %}
                <li>
                  <a class="nav-link" href="{% url 'admin:index' %}">Администрирование</a>
                </li>
                {% endif %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                </li>
                {% else %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'login' %}">Войти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="content container">
        {% block content %}
        {% endblock %}
    </div>

</body>

</html>

mysite/templates/base_management.html
<!DOCTYPE html>
<html lang="ru">

{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Координатор</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <link href="{% static '/open-iconic/font/css/open-iconic-bootstrap.css' %}"
          rel="stylesheet">
    <link rel="stylesheet"
          href="{% static 'base.css' %}">
    <script src="{% static '/js/jquery-3.4.1.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <span class="navbar-brand" href="#">Координатор</span>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Открыть меню">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbarCollapse" style>

            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'record_management' %}">Сводная</a>
                </li>
                <!--
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'doctor_list' %}">Врачи</a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'record_today' %}">Вызовы</a>
                </li>-->
            </ul>

            <!--
            <ul class="navbar-nav mr-auto">
                <li class="navbar-nav">
                    <a class="nav-link active" href="/about/">О проекте</a>
                </li>
            </ul>-->

            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <span class="navbar-text">
                        Добрый день,
                        {% if user.first_name %}
                            {{ user.first_name }}
                            {% if user.profile %}
                                {% if user.profile.middle_name %}
                                    {{ user.profile.middle_name }}
                                {% endif %}
                            {% endif %}
                        {% else %}
                            {{ user.username }}
                        {% endif %}
                        !
                    </span>
                </li>
                {% if user.is_superuser %}
                <li>
                  <a class="nav-link" href="{% url 'admin:index' %}">Администрирование</a>
                </li>
                {% endif %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                </li>
                {% else %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'login' %}">Войти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="content container">
        {% block content %}
        {% endblock %}
    </div>

</body>

</html>

mysite/templates/generic_detail.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ object.get_verbose_name }} - {{ object.name }}</h1>

    {% for field in object.get_detail_fields %}
    <div class="row">
        <div class="col">
            {{ field.verbose_name }}
        </div>
        <div class="col">
            {{ field.value }}
        </div>
    </div>
    {% endfor %}

{% endblock %}

mysite/templates/generic_list.html
{% extends 'base.html' %}

{% block content %}

    {% with object_list|first as object %}
    <h1>{{ object.get_verbose_name_plural }}</h1>
    {% endwith %}

    <table class="table table-striped table-bordered table-hover">
        <thead class="thead-dark text-center">
            <tr>
                {% with object_list|first as object %}
                {% for field in object.get_list_fields %}
                <th scope="col">{{ field.verbose_name }}</th>
                {% endfor %}
                {% endwith %}
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                {% for field in object.get_list_fields %}
                <td>
                    <!-- <a href="{ % url 'doctor_detail' pk=object.pk %}"> -->
                        {{ field.value }}
                    <!-- </a> -->
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}